import type { Metadata } from 'next';
import { Manrope } from 'next/font/google';
import './globals.css';
import Script from 'next/script';

const manrope = Manrope({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const MAP_API_KEY = process.env.MAP_API_KEY;

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ru">
      <body style={manrope.style}>
        {children}
        <Script
          src={`https://api-maps.yandex.ru/3.0/?apikey=${MAP_API_KEY}&lang=ru_RU`}
          type="module"
          strategy="beforeInteractive"
        />
      </body>
    </html>
  );
}
